# Generated by Django 3.2.4 on 2021-09-08 11:40

import django_otp_provider.lib.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_otp_provider', '0005_auto_20210908_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='key',
            field=models.CharField(max_length=50, unique=True, validators=[django_otp_provider.lib.utils.Transport.validator]),
        ),
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together={('token', 'key')},
        ),
    ]
