# Generated by Django 3.2.4 on 2021-09-01 17:09

import common.django_otp_provider.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='e884f6c5030749d9a3b74c664e6fdf38', max_length=250, unique=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('expire_at', models.DateTimeField(default=common.django_otp_provider.utils.expire_at)),
                ('attempts', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
