# Generated by Django 3.2.4 on 2021-09-09 09:24

from django.db import migrations, models
import django_otp_provider.django_otp_provider.utils


class Migration(migrations.Migration):

    dependencies = [
        ('django_otp_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='key',
            field=models.CharField(max_length=50, unique=True, validators=[django_otp_provider.django_otp_provider.utils.Transport.validator]),
        ),
    ]
