# Generated by Django 3.2.4 on 2021-09-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_otp_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_code_sended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(default='ca7520888bd34e35953e2a113ed928c3', max_length=250, unique=True),
        ),
    ]
