# Generated by Django 3.2.4 on 2021-09-07 10:03

import common.django_otp_provider.conf
import common.django_otp_provider.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_otp_provider", "0003_auto_20210902_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="key",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[common.django_otp_provider.utils.Transport.validator],
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="token",
            field=models.CharField(
                default="45c3f2538d244c8698cb8389692a9c14", max_length=250, unique=True
            ),
        ),
    ]
