# Generated by Django 3.2.4 on 2021-09-08 11:34

import common.django_otp_provider.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_otp_provider', '0004_auto_20210907_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='key',
            field=models.CharField(max_length=50, unique=True, validators=[common.django_otp_provider.utils.Transport.validator]),
        ),
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
